### ISSUE TITLE
Question on Splitting

### ISSUE THREAD

**Issue by extragoya** [VLL-HD/exact_information_bottleneck#6]
Hi - thanks for sharing your code! Quick conceptual question: I believe the architectures in this work do split off their latent codes using intermediate output nodes (unlike what's recommend in the FrEIA repo). I'm wondering why this was not done? Is it not really necessary?

**Comment by ardizzone** [comment]
Very good question!

In short, we found that it is not at all necessary for images as small as CIFAR10. In fact, even in our follow-up work on ImageNet images, we did not use it (https://arxiv.org/abs/2007.15036).

* It doesn't increase the number of parameters of the model as much as one would expect, because the width of the hidden layers of the subnetworks is the same regardless. The intermediate layers in the subnetworks contribute most to the model parameters.
* In terms of GPU usage, the training doesn't even fill a normal 11GB GPU, so it is also not needed from that standpoint. The practice of splitting of half of the latent dimensions early was introduced in RealNVP in 2015 I believe; the Nvidia GTX 980 from that era only had 4GB memory.
* We felt it unnecessarily complicates the code and the model
